AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  christian9a

  Sample SAM Template for christian9a

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  AltaBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: book/AltaBook/
      Handler: AltaBook.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        AltaBookEvent:
          Type: Api
          Properties:
            Path: /add
            Method: post

  EditBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: book/EditBook/
      Handler: EditBook.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        EditBookEvent:
          Type: Api
          Properties:
            Path: /edi
            Method: put

  RecuperarLibrosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: book/RecupearLibros/
      Handler: RecupearLibros.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        RecuperarLibrosEvent:
          Type: Api
          Properties:
            Path: /all
            Method: get

  RecuperarLibroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: book/RecuperarLibro/
      Handler: RecuperarLibro.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        RecuperarLibroEvent:
          Type: Api
          Properties:
            Path: /search
            Method: get

  EliminarLibroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: book/EliminarLibro/
      Handler: EliminarLibro.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        EliminarLibroEvent:
          Type: Api
          Properties:
            Path: /delete
            Method: delete


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
